// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxc0M9IS6T3FJzYCM0NBgdrEdw3BWvs-U',
    appId: '1:1059429691298:web:d336839f3026d0928d0cfb',
    messagingSenderId: '1059429691298',
    projectId: 'e-commerce-app-5776d',
    authDomain: 'e-commerce-app-5776d.firebaseapp.com',
    storageBucket: 'e-commerce-app-5776d.firebasestorage.app',
    measurementId: 'G-5BBRCYX1GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1HECbzPsCAwl_TIaNZ06mxsI4h5OSI_w',
    appId: '1:1059429691298:android:450db99513982b9d8d0cfb',
    messagingSenderId: '1059429691298',
    projectId: 'e-commerce-app-5776d',
    storageBucket: 'e-commerce-app-5776d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNcvQueIyLmTQJQXt1sbpkPjxGX0EV_A',
    appId: '1:1059429691298:ios:64b28109ed8fb2018d0cfb',
    messagingSenderId: '1059429691298',
    projectId: 'e-commerce-app-5776d',
    storageBucket: 'e-commerce-app-5776d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNcvQueIyLmTQJQXt1sbpkPjxGX0EV_A',
    appId: '1:1059429691298:ios:64b28109ed8fb2018d0cfb',
    messagingSenderId: '1059429691298',
    projectId: 'e-commerce-app-5776d',
    storageBucket: 'e-commerce-app-5776d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxc0M9IS6T3FJzYCM0NBgdrEdw3BWvs-U',
    appId: '1:1059429691298:web:67b2a854e468aa128d0cfb',
    messagingSenderId: '1059429691298',
    projectId: 'e-commerce-app-5776d',
    authDomain: 'e-commerce-app-5776d.firebaseapp.com',
    storageBucket: 'e-commerce-app-5776d.firebasestorage.app',
    measurementId: 'G-5LGDCQT1S3',
  );
}
